# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUBMITTER:      ROLE_USER
        ROLE_APPROVER:       ROLE_ADMIN
        ROLE_OPTIME_MASTER:  [ROLE_ADMIN, ROLE_SUPER_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                default_target_path: homepage
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true

            remember_me:
                secret: '%secret%'

    access_control:
        - { path: ^/(%locales.string%)/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%locales.string%)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%locales.string%)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%locales.string%)/deal-company/ajax-result/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%locales.string%)/state/ajax-result/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%locales.string%)/city/ajax-result/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%locales.string%)/create, role: ROLE_SUPER_ADMIN }
        - { path: ^/(%locales.string%)/list, role: ROLE_SUPER_ADMIN }
        - { path: ^/(%locales.string%)/, role: ROLE_USER }
        - { path: ^/(%locales.string%)/reports/, role: ROLE_OPTIME_MASTER }
        - { path: ^/exit, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, role: ROLE_USER }