<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Deal\Approver\ApproverInterface;
use AppBundle\Deal\Approver\ApproverRepositoryInterface;

/**
 * DealApproverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealApproverRepository extends \Doctrine\ORM\EntityRepository implements ApproverRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function findByDealId($id)
    {
        return $this->findOneBy(['deal' => $id]);
    }

    public function save(ApproverInterface $approver, $flush = true)
    {
        $this->_em->persist($approver);
        $flush and $this->_em->flush($approver);
    }
}
