<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\DealComment;
use Doctrine\ORM\EntityRepository;

/**
 * DealCommentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DealCommentRepository extends EntityRepository
{
    public function getLocaleForComment(DealComment $comment)
    {
        $dql = <<<DQL
SELECT submitter.language
FROM AppBundle:DealSubmitter submitter
JOIN AppBundle:Deal deal WITH deal.submitter = submitter
JOIN AppBundle:DealThread thread WITH thread.id = deal.id
JOIN AppBundle:DealComment comment WITH comment.thread = thread
WHERE
    comment.id = :comment
DQL;

        return $this->getEntityManager()->createQuery($dql)
            ->setParameter('comment', $comment->getId())
            ->getSingleScalarResult();
    }
}
