<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\EmailTemplate;
use Doctrine\ORM\EntityRepository;

/**
 * EmailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateRepository extends EntityRepository
{
    /**
     * @param           $code
     * @param bool|true $active
     *
     * @return null|EmailTemplate
     */
    public function findOneByCode($code, $active = true)
    {
        return $this->findOneBy(array(
            'code' => $code,
            'active' => $active,
        ));
    }
}
