<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Loyalty;
use Doctrine\ORM\EntityRepository;

/**
 * LoyaltyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoyaltyRepository extends EntityRepository
{
    /**
     * @param $code
     * @return null|Loyalty
     */
    public function findOneByCode($code)
    {
        $criteria = ['code' => $code];

        return parent::findOneBy($criteria);
    }

    public function getActiveLoyalties()
    {
        $criteria = ['isActive' => true];

        return parent::findBy($criteria);
    }

    public function save(Loyalty $loyalty)
    {
        $this->_em->persist($loyalty);
        $this->_em->flush($loyalty);
    }
}
