<?php

return array (
  'hash' => '1ca19eb8007f1070f85ba490ee9bc3e559b9bacc39416',
  'translations' => 
  array (
    'FOSUserBundle' => 
    array (
      'Bad credentials.' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '0514f1de58ebed720389f12b4a62354159af10661ad26',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Bad credentials.',
          'es' => 'Correo electrónico o contraseña incorrecta.',
        ),
      ),
      'Email:' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '24778d1f0e7e4236ab68d4a3acb2b00a59b9aa6d756af',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Email',
          'es' => 'Correo Electrónico',
        ),
      ),
      'resetting.email.message' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '823e8a8e7b56cf5c6c97ad1773eea70e59b07a75e9f07',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Hola %username%!

Para restablecer tu contraseña - por favor visita %confirmationUrl%

Atentamente,
HP VIP Club.',
          'es' => 'Hola %username%!

Para restablecer tu contraseña - por favor visita %confirmationUrl%

Atentamente,
HP VIP Club.',
        ),
      ),
      'resetting.request.username' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '86033247c45ec6ca5605f6f9dc602dea59b04baac8f07',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Email',
          'es' => 'Correo electrónico',
        ),
      ),
    ),
    'messages' => 
    array (
      'APPROVED_STATE' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'f5ca12740641113a35233148c7ff4d5c579bad43317a5',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Comments',
          'es' => 'Comentarios',
        ),
      ),
      'Email:' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '24778d1f0e7e4236ab68d4a3acb2b00a59b9aacf69d8d',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Email',
          'es' => 'Correo Electrónico',
        ),
      ),
      'Login' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'fc57805c60431db7aa2ac44a1730132759af106f6202e',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Login',
          'es' => 'Control de Acceso',
        ),
      ),
      'btn.save' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '8af63d3c7a36a2a2a8a46a456ab68e7d57912564456',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Save',
          'es' => 'Guardar',
        ),
      ),
      'btn.show_support_file' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '2ba4a835a200578c2555ab5fc251530057911b6209f4f',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'View Support',
          'es' => 'Ver Soporte',
        ),
      ),
      'label.approved' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'manASD0.14580979211796988',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Approved',
          'es' => 'Aprobado',
          'pt' => 'Aprovado',
        ),
      ),
      'label.authentication_error.message' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'd2cd006c6f24d6ec948f8d6b1648287c5787d8a2f1d27',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => '
An authorization problem has occurred, so it is not possible to display the current resource.',
          'es' => 'Ha ocurrido un problema de autorización, por lo que no es posible visualizar el recurso actual.',
        ),
      ),
      'label.change_status_to_won.description' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'a9530d06b664fc10bf92f5c4adf2e9745790f6ef62cd2',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Para establecer la oportunidad como ganada, usted debe cargar un soporte que confirme que realmente ha ganado dicha oportunidad.',
          'es' => 'Para establecer la oportunidad como ganada, usted debe cargar un soporte que confirme que realmente ha ganado dicha oportunidad.',
        ),
      ),
      'label.comments' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'f5ca12740641113a35233148c7ff4d5c579bad43317a5',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Comments',
          'es' => 'Comentarios',
        ),
      ),
      'label.deal_support.file' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '33c21d05144fa873ea46f85fbc54dad75790f47946808',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Support file',
          'es' => 'Archivo de soporte',
        ),
      ),
      'label.rejected_by' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'eb9577455f3ff5d17c3298ec00d579b7579032a217e1b',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Rejected by',
          'es' => 'Rechazado por',
        ),
      ),
      'label.to_be_approved_by' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '69d65f3e59ae9e1dd7c2e03fa210cabb5797bb0a9c9f6',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'To be Approved by',
          'es' => 'A ser Aprobado por',
        ),
      ),
      'phone.countryCode.not_blank' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '9721b6cdb1414d4884d06174a90a84ee59b49f4ed1e12',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Código del país no debería estar vacío.',
          'es' => 'Código del país no debería estar vacío.',
        ),
      ),
      'title.authentication_error' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '3d9bdc6f739bf37cffa75f2e1d12108a5787d84ec0ef0',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Authentication Error',
          'es' => 'Error de Authenticación',
        ),
      ),
      'title.change_password' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'b0aadce2340d77a4251777c3000e513159b07b387e717',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Change Password',
          'es' => 'Cambio de Contraseña',
        ),
      ),
    ),
    'phone_type' => 
    array (
      'Mobile' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '32abd45b5cb5e11a75dbb22ca1922b3959b9af5d84e27',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Mobile',
          'es' => 'Celular',
        ),
      ),
      'Office' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '0ab58d330e12108d4830e2a4212207a359b9aed3c71ff',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'Office',
          'es' => 'Oficina',
        ),
      ),
    ),
    'validators' => 
    array (
      'form.deal.support.file.invalid_mime_type' => 
      array (
        'files' => 
        array (
        ),
        'hash' => '604748f3bf64ec90b1a3b65cfcad22f857911fe1eca22',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'You can only upload a PDF or an Image',
          'es' => 'Solo puede subir un PDF o una Imagen',
        ),
      ),
    ),
  ),
);
